server:
  port: 9090
  ssl:
    enabled: true
    key-store: classpath:${AUTH_SERVER_KEYSTORE}
    key-store-type: ${STORE_TYPE}
    key-store-password: ${AUTH_SERVER_KEYSTORE_PASSWORD}
    trust-store: classpath:${AUTH_SERVER_TRUSTSTORE}
    trust-store-password: ${AUTH_SERVER_TRUSTSTORE_PASSWORD}
    trust-store-type: ${STORE_TYPE}
    client-auth: need

management:
    endpoints:
        web:
          exposure:
            include: prometheus,health
    endpoint:
        health:
        show-details: always


spring:
  datasource:
    url: ${AUTH_SERVER_DATASOURCE_URL}
    username: ${AUTH_SERVER_DATASOURCE_USERNAME}
    password: ${AUTH_SERVER_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: auth
      dialect: org.hibernate.dialect.PostgreSQLDialect

